### ISSUE TITLE
Reply to your post "RFC 4122/9562: UUID version 7 and 8 implementation"

### ISSUE THREAD

**Issue by sergeyprokhorenko** [picnixz/sphinx-zeta-suppress#4]
Hello Bénédikt,

This is the only available way to contact you and respond to your post [RFC 4122/9562: UUID version 7 and 8 implementation](https://discuss.python.org/t/rfc-4122-9562-uuid-version-7-and-8-implementation/56725). I was unable to reply via https://discuss.python.org/ due to their excessive restrictions.

The best choice is to take [uuid-rs/uuid](https://github.com/uuid-rs/uuid/issues/717) (it is perfect) as an example and add to it an optional formal parameter "timestamp offset" in milliseconds (positive or negative).

See also https://kodraus.github.io/rust/2024/06/24/uuid-v7-counters.html and https://www.reddit.com/r/rust/comments/1dn5ge4/uuid_now_properly_sorts_v7_ids/

**Comment by picnixz** [comment]
Oh! thank you for your reply. I will add a link to the Python issue as well in the discussion but the reason why I did not go for the rust implementation at first is because I wasn't sure how supported it is. But considering the references you linked and the other threads, I think most people prefer a fixed-bit length counter rather than a monotonous counter (it doesn't really matter to me, I just want to introduce something that is compatible in general).
